### PR TITLE
add options to show/hide search buttons when creating a widget

### PR DESCRIPTION
**Pull request by pbr0ck3r**
My company does not use the search buttons and they were causing some column formatting issues. So I added the options to remove those columns when adding/creating a widget for a dashboard.

### CODE REVIEW

**Comment by billmurrin** [comment]
Hey @pbr0ck3r, let me load this up and give it a go. Thanks for the contribution. Sounds like a great idea.

**Comment by pbr0ck3r** [comment]
@billmurrin the only thing I noticed that might need tweaking is existing widgets don't seem to get the new configuration. So existing widgets they just show the show table/chart and not show/display buttons.

**Comment by billmurrin** [comment]
Thanks @pbr0ck3r - I'll be merging these changes into 3.1 and adding a few other things. Thanks for the support!

**Comment by pbr0ck3r** [comment]
Awesome! Looking forward to seeing the updates you add. Let me know if there is anything you ever need help working on as I would gladly give a hand!

**Pull request merged**
